### ISSUE TITLE
Error: Can't join on 'time_slot_id' x 'time_slot_1' because of incompatible types (character / logical)

### ISSUE THREAD

**Issue by agricolamz** [langdoc/FRelan#3]
Hi, @nikopartanen, do you know what could be wrong?

```
library(tidyverse)
library(FRelan)
df <- read_eaf("AB-1927-Trybsz-MT.eaf")
```

**Comment by nikopartanen** [comment]
I'll check it tomorrow! Things are probably so out of date in the package that something trivial is breaking, although it can also be about specific tier template used in the file. Can you send me an example file to nikotapiopartanen@gmail.com? It can be a dummy file with few annotations only, as long as the structure is the same.

**Comment by nikopartanen** [comment]
Thanks for the example file! The heart of the problem is that the function expects a very specific tier template which we have used in our Komi project, and is quite inflexible to anything else. [Here](https://github.com/langdoc/FRechdoc/wiki/ELAN-tiers) is a screenshot and other info of our structures. We use this in different projects so that we can run our annotation pipeline on top of that. This is described more [here](https://github.com/langdoc/elan-fst).

However, we have also migrated quite far from how this R package deals with everything, and I've planned to polish it when I have time. Anyway, the current method I use to parse our project files looks like this:

```
library(tidyverse)
library(tidytext)
library(FRelan)

read_custom_eaf <- function(path_to_file){
        
        ref <- FRelan::read_tier(eaf_file = path_to_file, linguistic_type = "refT") %>%
                dplyr::select(content, annot_id, participant, time_slot_1, time_slot_2) %>%
                dplyr::rename(ref = content) %>%
                dplyr::rename(ref_id = annot_id)
        
        orth <- FRelan::read_tier(eaf_file = path_to_file, linguistic_type = "orthT") %>%
                dplyr::select(content, annot_id, ref_id, participant) %>%
                dplyr::rename(orth = content) %>%
                dplyr::rename(orth_id = annot_id)
        
        elan <- left_join(ref, orth, by = c("ref_id", "participant")) %>% 
                select(time_slot_1, time_slot_2, everything(), -ends_with('_id'))
        
        time_slots <- FRelan::read_timeslots(path_to_file)
        
        elan %>% left_join(time_slots %>% rename(time_slot_1 = time_slot_id), by = "time_slot_1") %>%
                rename(time_start = time_value) %>%
                left_join(time_slots %>% rename(time_slot_2 = time_slot_id), by = "time_slot_2") %>%
                rename(time_end = time_value) %>%
                select(participant, time_start, time_end, everything(), -starts_with('time_slot_')) %>%
                mutate(session_name = str_extract(path_to_file, '[^/]+(?=.eaf)')) %>%
                mutate(filename = path_to_file)
        
}

read_custom_eaf('~/Desktop/example.eaf') %>%
        unnest_tokens(input = orth,
                      output = "token", drop = FALSE, to_lower = FALSE) %>%
        select(token, everything())
```

I added [here](https://github.com/langdoc/FRelan/files/4274731/example.zip) an example file where at least the code above should work! This results in something like this:

![image](https://user-images.githubusercontent.com/6486495/75665861-81688700-5c7d-11ea-88f8-3a0dda955cfc.png)

This also rises questions such as how do we tokenize the most reliable way this kind of field work data etc. I usually set this kind of parsing up as a loop where I inspect the ELAN files while I'm working with them. 

Anyway I also often wouldn't write the result our of further pipeline into ELAN file itself, but just annotate it on the fly with [uralicNLP](https://github.com/mikahama/uralicNLP) package. I use [feather](https://github.com/wesm/feather) to get the result back to R.

Few other comments:

- I probably use the participant tag too often, I'm rather sure the participant name is now picked up from there and not tier-prefix or something in tier name. Our files always have this filled, but in principle the same information is in tier names.
- I would usually set things up so that one tier type defines strictly one kind of data, so each translation language and each content type would have their own tier type. Now the example file you sent has tier type 1 on three different types of content (Uwagi, Objasnienia and Watpliwosci), and default-lt is for two tiers. This may be more difficult to parse, although maybe there are easy and clever ways, and with one speaker it doesn't really matter. I think the benefit of setting up many tier types and using them parallel for each speaker gets most obvious when there are several speakers, so one can have a function that processes each speaker same way.

**Comment by agricolamz** [comment]
Thank you, Niko! @rvwfels, look here

**Comment by agricolamz** [comment]
@nikopartanen, I also added the less complicated [function `eaf_to_df()`](https://github.com/agricolamz/phonfieldwork/blob/master/R/eaf_to_df.R) for reading ELAN to R to the development version of [`phonfieldwork`](https://github.com/agricolamz/phonfieldwork). It is doing slightly different job, but could be useful once. Greetings and love!

**Comment by nikopartanen** [comment]
Great, @agricolamz! Your solution is really nice! All the best for you as well!
